jenkins2-primary:
  image: "index.tenxcloud.com/zhongjianxin/jenkins-master:v1.0"
  labels:
    io.rancher.sidekicks: jenkins2-plugins,jenkins2-datavolume
    io.rancher.container.hostname_override: container_name
    # io.rancher.scheduler.affinity:host_label: wise2builder=ci
  volumes_from:
    - jenkins2-plugins
    - jenkins2-datavolume
jenkins2-plugins:
  image: "index.tenxcloud.com/zhongjianxin/jenkins-plugin:v1.0"
  labels:
    io.rancher.container.start_once: true
    # io.rancher.scheduler.affinity:host_label: wise2builder=ci
jenkins2-datavolume:
  image: "index.tenxcloud.com/zhongjianxin/jenkins-data:v1.0"
  volumes:
    - /var/jenkins_home
  labels:
    io.rancher.container.start_once: true
    # io.rancher.scheduler.affinity:host_label: wise2builder=ci
  entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
