.catalog:
  name: Jenkins2 Swarm
  version: "0.0.1"
  description: |
    Containers that run the slave plugin.
  questions:
    - variable: jenkins_user
      label: "Jenkins username"
      type: "string"
      required: false
      description: |
        Username to authenticate to a secured Jenkins host with.
    - variable: jenkins_pass
      label: "Jenkins password"
      type: "string"
      required: false
      description: |
        Password to authenticate to a secured Jenkins host with.
    - variable: swarm_executors
      required: false
      type: "string"
      description: |
        Number of executors on the swarm. Default is #cpus
    - variable: jenkins_service
      label: "Jenkins Server"
      type: "service"
      required: true
      description: |
        Service that is running Jenkins CI server
